### PR TITLE
Modify calculation of Z score from Pval for Scott

### PR DESCRIPTION
**Pull request by kdkorthauer**
The calculation of Z-score to p-value should consider the sign of the effect.

### CODE REVIEW

**Comment by kdkorthauer** [comment]
Related to Issue #8

**Comment by pkimes** [comment]
Serious question: are the p-values always going to be for two-sided tests? Obviously true for our current simulated data, but is this true for all of the real data types we're considering?

**Comment by kdkorthauer** [comment]
Not necessarily. Maybe instead of having the wrapper calculate the Z scores in a general way, it should take as input Z scores. Then the Z score can be calculated specific to the problem at hand (eg one versus two sided, from pvalues or effect sizes and SE).

**Comment by pkimes** [comment]
Will open a separate issue to add z-scores as input to wrappers in future.

**Pull request merged**
